
insert_501= "Internal Server Error while Inserting Data."
insert_200= "Inserted Successfully"
update_501= "Internal Server Error while Updating Data."
update_200= "Updated Successfully"
getAll_501= "Internal Server Error while Fetching All Data."
getAll_200= "Fetching Successfully"
getById_501= "Internal Server Error while Fetching Data By Id."
getById_200= "Fetching Successfully By Id"
delete_501= "Internal Server Error while Deleting Data."
delete_200= "Deleted Successfully"
execution_501="Error while executing query"
execution_200="Query executed Successfully"
queryError_501="Error in Sql syntax"
filetye="File Not Allowed"
saveImg="Error in Image saving"
shedulerErr="Error while implementing scheduler"
